################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
autogen \
bma \
gecko_sdk_4.1.1/app/common/util/app_log \
gecko_sdk_4.1.1/platform/Device/SiliconLabs/EFR32MG22/Source \
gecko_sdk_4.1.1/platform/common/src \
gecko_sdk_4.1.1/platform/common/toolchain/src \
gecko_sdk_4.1.1/platform/emdrv/dmadrv/src \
gecko_sdk_4.1.1/platform/emdrv/gpiointerrupt/src \
gecko_sdk_4.1.1/platform/emdrv/spidrv/src \
gecko_sdk_4.1.1/platform/emlib/src \
gecko_sdk_4.1.1/platform/service/device_init/src \
gecko_sdk_4.1.1/platform/service/iostream/src \
gecko_sdk_4.1.1/platform/service/sleeptimer/src \
gecko_sdk_4.1.1/platform/service/system/src \
gecko_sdk_4.1.1/platform/service/udelay/src \
gecko_sdk_4.1.1/util/third_party/printf \
gecko_sdk_4.1.1/util/third_party/printf/src \
red/edge-impulse-sdk/CMSIS/DSP/Source/BasicMathFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/BayesFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/CommonTables \
red/edge-impulse-sdk/CMSIS/DSP/Source/ComplexMathFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/ControllerFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/DistanceFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/FastMathFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/FilteringFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/InterpolationFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/MatrixFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/QuaternionMathFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/SVMFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/SupportFunctions \
red/edge-impulse-sdk/CMSIS/DSP/Source/TransformFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/ActivationFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/BasicMathFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/ConcatenationFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/ConvolutionFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/FullyConnectedFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/NNSupportFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/PoolingFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/ReshapeFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/SVDFunctions \
red/edge-impulse-sdk/CMSIS/NN/Source/SoftmaxFunctions \
red/edge-impulse-sdk/classifier \
red/edge-impulse-sdk/dsp/dct \
red/edge-impulse-sdk/dsp/image \
red/edge-impulse-sdk/dsp/kissfft \
red/edge-impulse-sdk/dsp \
red/edge-impulse-sdk/porting/arduino \
red/edge-impulse-sdk/porting/brickml \
red/edge-impulse-sdk/porting/espressif/ESP-NN/src/activation_functions \
red/edge-impulse-sdk/porting/espressif/ESP-NN/src/basic_math \
red/edge-impulse-sdk/porting/espressif/ESP-NN/src/convolution \
red/edge-impulse-sdk/porting/espressif/ESP-NN/src/fully_connected \
red/edge-impulse-sdk/porting/espressif/ESP-NN/src/pooling \
red/edge-impulse-sdk/porting/espressif/ESP-NN/src/softmax \
red/edge-impulse-sdk/porting/espressif \
red/edge-impulse-sdk/porting/ethos-core-driver/src \
red/edge-impulse-sdk/porting/himax \
red/edge-impulse-sdk/porting/infineon-psoc62 \
red/edge-impulse-sdk/porting/mbed \
red/edge-impulse-sdk/porting/mingw32 \
red/edge-impulse-sdk/porting/posix \
red/edge-impulse-sdk/porting/raspberry \
red/edge-impulse-sdk/porting/renesas-ra6m5 \
red/edge-impulse-sdk/porting/seeed-vision-ai \
red/edge-impulse-sdk/porting/silabs \
red/edge-impulse-sdk/porting/sony \
red/edge-impulse-sdk/porting/stm32-cubeai \
red/edge-impulse-sdk/porting/synaptics \
red/edge-impulse-sdk/porting/ti \
red/edge-impulse-sdk/porting/zephyr \
red/edge-impulse-sdk/tensorflow/lite/c \
red/edge-impulse-sdk/tensorflow/lite/core/api \
red/edge-impulse-sdk/tensorflow/lite/kernels/internal \
red/edge-impulse-sdk/tensorflow/lite/kernels \
red/edge-impulse-sdk/tensorflow/lite/micro \
red/edge-impulse-sdk/tensorflow/lite/micro/kernels \
red/edge-impulse-sdk/tensorflow/lite/micro/memory_planner \
red/tflite-model \

